<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FeasaWpfDemo</RootNamespace>
    <AssemblyName>FeasaWpfDemo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FeasaLedAnalyser" Version="0.1.0" />
  </ItemGroup>

</Project>
